eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9204
spring:
  application:
    name: youqu-service-other
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/youqu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  cloud:  # Spring Cloud Stream 相关配置
    stream:
      bindings: # exchange与queue绑定
        email_input: # 邮件消费者设置input
          destination: email.exchange # exchange
          content-type: application/json # 消息传输类型
          group: email.queue  # queue
          binder: rabbit
        log_input: # 日志消费者设置input
          destination: log.exchange
          content-type: application/json
          group: log.queue
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest

  redis:
    host: 127.0.0.1   #redis相关配置 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 3
        max-idle: 3
        max-wait: 6000ms # -1ms不超时
        min-idle: 0
    #password: guest

#  rabbitmq: # RabbitMQ相关配置
#    addresses: 127.0.0.1:5672    #127.0.0.1:5672
#    username: guest
#    password: 25802580


  # QQ邮箱设置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1027796553@qq.com #发送邮件的邮箱地址
    password: fxqdwkkfvsfrbcjf #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1027796553@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.auth: true
    default-encoding: utf-8

# 邮件验证码过期时间
time:
  minute: 10


# 七牛云相关配置
qiniu:
  access: B9jCD08z9VrlIudJv7Tn-gBHGpH4m9g8j5AmePUi
  secret: yRxxOiSAKyJD5Jb_GONqDJxH3pcYL_IlQGrr237d
  bucket: hexhe
  url: http://rc0oennsy.hn-bkt.clouddn.com/


# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名法

#日志打印
logging:
  level:
    cn.zdxh.other.log.mapper : debug